-- createCity
DROP PROCEDURE IF EXISTS createCity;
DELIMITER //
CREATE PROCEDURE createCity(
in pcityId varchar(50))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
  GET STACKED DIAGNOSTICS CONDITION 1 @p1 = RETURNED_SQLSTATE, @p2 = MESSAGE_TEXT;
  SELECT @p1, @p2;
  ROLLBACK;
END;
START TRANSACTION;
IF NOT pcityId REGEXP '^[a-zA-Z0-9]*$'
THEN SIGNAL SQLSTATE '45000'
     SET MESSAGE_TEXT = 'CITY-000';
ELSEIF EXISTS ( SELECT * 
			FROM city
            WHERE city_id = pcityId )
THEN SIGNAL SQLSTATE '45000'
     SET MESSAGE_TEXT = 'CITY-001';
ELSE 
    INSERT INTO city VALUES (pcityId);
END IF;

END //
DELIMITER ;
