-- createCityCenterCourt(courtId, cityId, centerId)

DROP PROCEDURE IF EXISTS createCityCenterCourt;
DELIMITER //
CREATE PROCEDURE createCityCenterCourt(
in pcourtId varchar(50), in pcityId varchar(50), in pcenterId varchar(50))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
  GET STACKED DIAGNOSTICS CONDITION 1 @p1 = RETURNED_SQLSTATE, @p2 = MESSAGE_TEXT;
  SELECT @p1, @p2;
  ROLLBACK;
END;
  
START TRANSACTION;

IF NOT pcityId REGEXP '^[a-zA-Z0-9]*$'
THEN 
	 SIGNAL SQLSTATE '45000'
     SET MESSAGE_TEXT = 'CRT-000';
ELSEIF NOT pcenterId REGEXP '^[a-zA-Z0-9]*$'
THEN 
	 SIGNAL SQLSTATE '45000'
     SET MESSAGE_TEXT = 'CRT-001';
ELSEIF NOT pcourtId REGEXP '^[a-zA-Z0-9]*$'
THEN 
	 SIGNAL SQLSTATE '45000'
     SET MESSAGE_TEXT = 'CRT-002';
ELSEIF NOT EXISTS ( SELECT * FROM city WHERE city_id = pcityId)
THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT ="CRT-003";
ELSEIF NOT EXISTS (SELECT * FROM center WHERE center_id = pcenterId)
THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT ="CRT-004";
ELSEIF
	EXISTS (SELECT * FROM court WHERE court_id = pcourtId)
THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT ="CRT-005";
ELSE INSERT INTO court VALUES (pcourtId, pcityId, pcenterId);
END IF;
END //
DELIMITER ;
