-- createStaff(staffId, cityId, centerId)
DROP PROCEDURE IF EXISTS createStaff;
DELIMITER //
CREATE PROCEDURE createStaff(
in pstaffId varchar(50), in pcityId varchar(50), in pcenterId varchar(50))
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
  GET STACKED DIAGNOSTICS CONDITION 1 @p1 = RETURNED_SQLSTATE, @p2 = MESSAGE_TEXT;
  SELECT @p1, @p2;
  ROLLBACK;
END;
  
START TRANSACTION;
IF NOT pcityId REGEXP '^[a-zA-Z0-9]*$'
THEN 
	 SIGNAL SQLSTATE '45000'
     SET MESSAGE_TEXT = 'CS-000';
ELSEIF NOT pcenterId REGEXP '^[a-zA-Z0-9]*$'
THEN 
	 SIGNAL SQLSTATE '45000'
     SET MESSAGE_TEXT = 'CS-001';
ELSEIF NOT pstaffId REGEXP '^[a-zA-Z0-9]*$'
THEN 
	 SIGNAL SQLSTATE '45000'
     SET MESSAGE_TEXT = 'CS-002';
ELSEIF NOT EXISTS (SELECT * FROM city WHERE city_id = pcityId)
THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT ="CS-003";
ELSEIF
	NOT EXISTS (SELECT * FROM center WHERE center_id = pcenterId)
THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT ="CS-004";
ELSEIF
	EXISTS (SELECT * FROM staff WHERE staff_id = pstaffId)
THEN
	SIGNAL SQLSTATE '45000'
	SET MESSAGE_TEXT ="CS-005";
ELSE INSERT INTO staff VALUES (pstaffId, pcityId, pcenterId);
END IF;
END //
DELIMITER ;
DELIMITER ;