DROP PROCEDURE IF EXISTS getcity;
DELIMITER //
CREATE PROCEDURE getcity()
BEGIN
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
  GET STACKED DIAGNOSTICS CONDITION 1 @p1 = RETURNED_SQLSTATE, @p2 = MESSAGE_TEXT;
  SELECT @p1, @p2;
  ROLLBACK;
END;
START TRANSACTION;
-- select all cities --
select * from city;
END //
DELIMITER ;

call getcity();